apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  labels:
    openvpn: ${OVPN_CN}
spec:
  selector:
    matchLabels:
      openvpn: ${OVPN_CN}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        openvpn: ${OVPN_CN}
    spec:
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      restartPolicy: Always
      containers:
      - name: openvpn
        image: quay.io/plange/openvpn:latest
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/openvpn/pki
          name: openvpn-pki
        - mountPath: /etc/openvpn/crl
          name: openvpn-crl
        - mountPath: /etc/openvpn/ccd
          name: openvpn-ccd
        - mountPath: /etc/openvpn/portmapping
          name: openvpn-portmapping
        - mountPath: /etc/openvpn/status
          name: openvpn-status
        - mountPath: /tmp/openvpn.tmpl
          name: openvpn-config
          subPath: template
        ports:
        - name: openvpn
          containerPort: 1194
          protocol: TCP
        env:
        - name: OVPN_TEMPLATE
          value: /tmp/openvpn.tmpl
        - name: PODIPADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OVPN_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: openvpn-settings
              key: serverurl
        - name: OVPN_K8S_SERVICE_NETWORK
          valueFrom:
            configMapKeyRef:
              name: openvpn-settings
              key: servicecidr
        - name: OVPN_K8S_POD_NETWORK
          valueFrom:
            configMapKeyRef:
              name: openvpn-settings
              key: podcidr
        - name: OVPN_K8S_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: openvpn-settings
              key: domain
        - name: OVPN_STATUS
          valueFrom:
            configMapKeyRef:
              name: openvpn-settings
              key: statusfile
      volumes:
      - name: openvpn-config
        configMap:
          name: openvpn-config
      - name: openvpn-pki
        secret:
          secretName: openvpn-pki
          defaultMode: 0400
      - name: openvpn-ccd
        configMap:
          name: openvpn-ccd
      - name: openvpn-crl
        configMap:
          defaultMode: 0555
          name: openvpn-crl
      - name: openvpn-portmapping
        configMap:
          name: openvpn-portmapping
      - name: openvpn-status
        emptyDir: {}
